<?php
declare(strict_types=1);

namespace AfricaGates\Services;

use AfricaGates\Support\ChallengeEnum as E;

/**
 * Every public word a challenge says, generated from its own row.
 *
 * ══════════════════════════════════════════════════════════════════════════════
 * A PORT OF `derive()` AND `renderVals()` IN `designs/ChallengePage.dc.html`
 * ══════════════════════════════════════════════════════════════════════════════
 *
 * The handoff requires it (§3): "Copy is generated by `ChallengeCopy::for($challenge)`.
 * Port `derive()` from `ChallengePage.dc.html` exactly." The strings below are those
 * two functions', character for character, down to the typographic apostrophes — a
 * paraphrase here would be a page saying something no designer wrote, and the promise
 * sentence is a term of a contest that pays money.
 *
 * ── WHY THIS IS GENERATED AND NOT TYPED ─────────────────────────────────────
 *
 * The alternative is an admin typing "The first 11 people to get 10 different
 * nominees verified each win ₦6,000" into a box beside the fields that say 11, 10 and
 * 6000. The day somebody raises the cap to 15, the sentence still says 11 — on the
 * page a contestant reads to decide whether to take part, and in the terms they are
 * agreeing to.
 *
 * This codebase has paid for that four times. The settings screen explained the
 * default scoring basis with a DIFFERENT basis's arithmetic, 157 points out, on the
 * screen where an operator picks it; the handbook's figures are looped from the rules
 * for the same reason. **Anything typed here that could have been computed is a bug
 * waiting to happen.**
 *
 * So an admin may APPEND rules (`extra_rules`) and may never replace the generated
 * ones. {@see rules()}.
 *
 * ── THE THREE PLACES THIS DELIBERATELY DOES NOT FOLLOW THE DC ───────────────
 *
 * 1. **No hexes.** `renderVals()` returns `stInk:'#1a6118'`, `ctaBg:c.accent` and so
 *    on, because a design comp carries its own palette inline. §0.4 of the handoff
 *    forbids a new colour and this repo's own rule is blunter: a bare hex is not a
 *    colour, it comes from `Support\Accent` or a theme token and nowhere else. So the
 *    state is returned as a KEY and a label; the stylesheet paints it.
 * 2. **`timeLeft` is computed, not stored.** The DC reads `c.days`, a number typed
 *    into its fixture, and hardcodes `'Starts 5 Oct'`. A countdown typed onto a row is
 *    the §19 shape with a clock attached — it is right the day it is saved and wrong
 *    every day after. It is derived from `ends_at`/`starts_at` here, with the fixture's
 *    own `days` as the fallback that keeps the demo configs reproducible.
 * 3. **`verb` is not ported.** `derive()` opens with `const verb = {...}[c.action]`
 *    and never uses it — the name appears exactly once in the whole file, in its own
 *    declaration. Carrying a vestige into a service that has none would be writing the
 *    bug this codebase sweeps for.
 */
final class ChallengeCopy
{
    /**
     * The singular and plural of what a person collects, per action.
     *
     * The DC's `unit` map. `attend` is not in it — see {@see steps()}.
     *
     * @var array<string,array{0:string,1:string}>
     */
    private const UNITS = [
        E::ACTION_NOMINATE => ['different nominee', 'different nominees'],
        E::ACTION_VOTE     => ['category', 'categories'],
        E::ACTION_REFER    => ['paid ticket', 'paid tickets'],
        E::ACTION_GIVE     => ['gift', 'gifts'],
    ];

    /** The DC's `ST` map, minus the hexes. The key is what the stylesheet reads. */
    private const STATE_LABELS = [
        'open'     => 'Open',
        'full'     => 'Full',
        'ended'    => 'Ended',
        'upcoming' => 'Starts soon',
    ];

    /**
     * Everything the public page prints, for one challenge.
     *
     * @param array<string,mixed> $c   the challenge row, or a `ChallengeDemo` config
     * @param array<string,mixed> $ctx what the viewer's situation adds:
     *        `state` (the row's status), `signed_in`, `claimed`, `mine`, `now`
     * @return array<string,mixed>
     */
    public static function for(array $c, array $ctx = []): array
    {
        $action = (string) ($c['action'] ?? E::ACTION_NOMINATE);
        $mode   = (string) ($c['mode'] ?? E::MODE_FIRST);
        $target = max(1, (int) ($c['target'] ?? 1));
        $cap    = (int) ($c['cap'] ?? 0);

        // ── The DC's own state arithmetic, which is not just the status column ──
        // `full = st==='full' || (mode==='first' && claimed >= cap)`. A challenge whose
        // last prize was claimed a second ago is full before any sweep has written the
        // word, and the page must not go on inviting people into a race that is over.
        $claimed = (int) ($ctx['claimed'] ?? $c['claimed'] ?? 0);
        $capped  = $mode === E::MODE_FIRST;          // the DC's `capped`
        $st      = (string) ($ctx['state'] ?? $c['status'] ?? 'open');

        $full     = $st === E::ST_FULL || ($capped && $cap > 0 && $claimed >= $cap);
        $ended    = $st === E::ST_ENDED;
        $upcoming = $st === E::ST_UPCOMING;
        $open     = !$full && !$ended && !$upcoming;
        $signedIn = (bool) ($ctx['signed_in'] ?? false);
        $joined   = $signedIn && $open;

        // The meter fills to the cap when the challenge is full, so a race that closed
        // on a late disqualification does not draw eleven prizes with ten dots lit.
        $shown = ($full && $capped && $cap > 0) ? $cap : $claimed;

        $stateKey = $full ? 'full' : (isset(self::STATE_LABELS[$st]) ? $st : 'open');

        $unit = self::UNITS[$action] ?? self::UNITS[E::ACTION_NOMINATE];
        // The DC: `c.target === 1 ? unit[0] : unit[1]`. A target of one is a real
        // configuration — "bring one paid ticket" — and "1 paid tickets" is the kind of
        // sentence that makes a campaign look unfinished.
        $u = $target === 1 ? $unit[0] : $unit[1];

        $prize = self::prize($c);
        $mine  = (int) ($ctx['mine'] ?? $c['mine'] ?? 0);
        $days  = self::daysLeft($c, $ctx);

        $mineLine = $action === E::ACTION_REFER
            ? $mine . ' of ' . $target . ' paid tickets'
            : $mine . ' of ' . $target . ' verified';

        return [
            // ── identity ──
            'state'         => $stateKey,
            'state_label'   => self::STATE_LABELS[$stateKey],
            'u'             => $u,
            'prize_big'     => $prize['big'],
            'prize_unit'    => $prize['unit'],
            'terms_version' => (string) ($c['terms_version'] ?? $c['termsV'] ?? ''),

            // ── the sentence that is also a term of the contest ──
            'promise' => self::promise($c, $u, $prize['big'], $prize['unit']),
            'facts'   => self::facts($c, $u, $prize, $capped, $ended),

            // ── the meter ──
            'has_meter'   => $capped,
            'cap'         => $cap,
            'claimed'     => $shown,
            'meter_title' => self::meterTitle($c, $capped, $full, $shown),
            'meter_aria'  => $shown . ' of ' . $cap . ' prizes claimed',
            'time_left'   => self::timeLeft($c, $upcoming, $ended, $full, $days),

            // ── this viewer ──
            'mine'     => $mineLine,
            'mine_pct' => min(100.0, round($mine / $target * 100, 2)),
            'joined'   => $joined,

            // ── the one control on the page ──
            'cta'         => self::cta($action, $upcoming, $ended, $full, $joined),
            'cta_href'    => self::ctaHref($action, $upcoming, $ended, $full, $joined, $c),
            'cta_primary' => !($full || $ended),
            'cta_note'    => self::ctaNote($cap, $upcoming, $ended, $full, $joined),
            'bar_sub'     => self::barSub($cap, $shown, $days, $full, $joined, $capped, $mineLine),

            // ── the sections ──
            'steps'       => self::steps($c, $u),
            'count_title' => $action === E::ACTION_REFER ? 'What counts' : 'What counts as verified',
            'rules'       => self::rules($c, $u),
            'win_title'   => $mode === E::MODE_TOP ? 'Leading now' : 'Winners so far',
            'win_sub'     => match ($mode) {
                E::MODE_TOP  => 'Updated every hour',
                E::MODE_DRAW => 'Draw on ' . self::drawDate($c),
                default      => 'In the order they qualified',
            },
            'empty_title' => $mode === E::MODE_DRAW
                ? 'The draw happens on ' . self::drawDate($c)
                : 'Nobody has qualified yet',
            'empty_sub'   => $mode === E::MODE_DRAW
                ? 'Everyone who gets ' . $target . ' ' . $u . ' verified before the close goes into the draw.'
                : 'The first winner will appear here the moment their entry is verified.',
            'faq'         => self::faq($c),
        ];
    }

    /**
     * One line for the compact strip on a scoped award, event or nominee page.
     *
     * The same figures as the card, in the one sentence that fits beside something
     * else — generated here rather than in the partial so a strip can never promise a
     * different prize from the page it links to.
     */
    public static function strip(array $c, array $ctx = []): array
    {
        $v = self::for($c, $ctx);

        return [
            'title' => (string) ($c['title'] ?? ''),
            'line'  => trim($v['prize_big'] . ' ' . $v['prize_unit']) . ' · '
                     . (int) ($c['target'] ?? 1) . ' ' . $v['u'],
            'state' => $v['state'],
            'state_label' => $v['state_label'],
            'cta'   => $v['cta'],
            'href'  => '/challenges/' . (string) ($c['slug'] ?? ''),
        ];
    }

    // ══════════════════════════════════════════════════════════════════════════
    // The sentence that is also a term of the contest
    // ══════════════════════════════════════════════════════════════════════════

    /**
     * "The first 11 people to get 10 different nominees verified each win ₦6,000."
     *
     * Three shapes, one per mode, and they are not interchangeable: `first` promises a
     * race, `top` promises a ranking at a deadline, `draw` promises a lottery among
     * everybody who finished. Somebody decides whether to spend an evening on this by
     * reading this sentence.
     */
    private static function promise(array $c, string $u, string $big, string $unit): string
    {
        $mode   = (string) ($c['mode'] ?? E::MODE_FIRST);
        $target = (int) ($c['target'] ?? 1);
        $cap    = (int) ($c['cap'] ?? 0);
        $type   = (string) ($c['prize_type'] ?? E::PRIZE_CASH_EACH);

        if ($mode === E::MODE_TOP) {
            // The DC takes everything before the first comma of the close — "30 Nov"
            // out of "30 Nov, 23:59 EAT" — because a promise does not need a minute.
            $by = explode(',', (string) ($c['ends'] ?? ''))[0];

            return 'The top ' . $cap . ' by ' . $by . ' win ' . $big . ' ' . $unit
                 . '. Every paid ticket through your link counts.';
        }

        if ($mode === E::MODE_DRAW) {
            return (int) ($c['draw_count'] ?? 0) . ' people drawn at random from everyone who gets '
                 . $target . ' ' . $u . ' verified win ' . $big . ' ' . $unit . '.';
        }

        // `cash_each` already reads "each" in the unit, so `first` does not repeat it —
        // the DC's own conditional, and without it the sentence ends "win ₦6,000 each
        // each".
        return 'The first ' . $cap . ' people to get ' . $target . ' ' . $u
             . ' verified each win ' . $big . ($type === E::PRIZE_CASH_EACH ? '' : ' ' . $unit) . '.';
    }

    /**
     * The prize as a figure and a unit: "₦6,000" + "each", "5,000" + "points".
     *
     * @return array{big:string,unit:string}
     */
    private static function prize(array $c): array
    {
        $type   = (string) ($c['prize_type'] ?? E::PRIZE_CASH_EACH);
        $amount = (int) ($c['prize_amount'] ?? 0);

        return [
            'big' => match ($type) {
                E::PRIZE_POINTS  => self::fmt($amount),
                E::PRIZE_TICKETS => (string) $amount,
                // The currency is a SYMBOL on the row (₦, KSh, GH₵), not a code,
                // because the design prints it joined to the figure with no space.
                default          => (string) ($c['prize_currency'] ?? '') . self::fmt($amount),
            },
            'unit' => match ($type) {
                E::PRIZE_POINTS    => 'points',
                E::PRIZE_TICKETS   => (string) ($c['prize_label'] ?? ''),
                E::PRIZE_CASH_EACH => 'each',
                default            => 'shared',
            },
        ];
    }

    /** @return list<array{k:string,v:string}> Prize · Winners · To qualify · Ends */
    private static function facts(array $c, string $u, array $prize, bool $capped, bool $ended): array
    {
        $cap = (int) ($c['cap'] ?? 0);

        $winners = $capped
            ? 'First ' . $cap
            : ((string) ($c['mode'] ?? '') === E::MODE_TOP
                ? 'Top ' . $cap
                : (int) ($c['draw_count'] ?? 0) . ', by draw');

        return [
            ['k' => 'Prize',      'v' => trim($prize['big'] . ' ' . $prize['unit'])],
            ['k' => 'Winners',    'v' => $winners],
            ['k' => 'To qualify', 'v' => (int) ($c['target'] ?? 1) . ' ' . $u],
            ['k' => $ended ? 'Ended' : 'Ends', 'v' => (string) ($c['ends'] ?? '')],
        ];
    }

    // ══════════════════════════════════════════════════════════════════════════
    // How to take part
    // ══════════════════════════════════════════════════════════════════════════

    /**
     * Three steps, per action.
     *
     * ── A GAP IN THE DESIGN, PORTED RATHER THAN PAPERED OVER ────────────────
     *
     * `derive()` defines steps for `nominate` and `refer` only and falls back to `[]`
     * for everything else — so a `vote`, `give` or `attend` challenge renders an empty
     * "How to take part" on the page somebody opens to find out how to take part. The
     * same hole is in the per-action `rules` below, where it is worse: those are the
     * published terms of a contest.
     *
     * This returns the DC's answer exactly, including the empty one, because inventing
     * sentences for a vote challenge would be putting unreviewed words on a public page
     * — and the handoff's own rule is "if something can't be matched, stop and ask".
     * `ChallengeCopyTest` pins the gap so it reads as a question put to the designer
     * rather than an oversight here, and the admin builder must refuse to publish those
     * three actions until it is answered.
     *
     * @return list<array{n:string,t:string,s:string}>
     */
    private static function steps(array $c, string $u): array
    {
        $target = (int) ($c['target'] ?? 1);

        $raw = match ((string) ($c['action'] ?? E::ACTION_NOMINATE)) {
            E::ACTION_NOMINATE => [
                ['Sign in or create your account', 'Free. Verify your phone number with a code.'],
                ['Nominate ' . $target . ' ' . $u,
                 'For ' . (string) ($c['award'] ?? '') . ', in ' . (string) ($c['cats'] ?? '')
                 . ', with every field complete.'],
                ['Get them verified', 'Each nominee confirms, and our team checks the details.'],
            ],
            E::ACTION_REFER => [
                ['Sign in or create your account', 'Free. Verify your phone number with a code.'],
                ['Share your event link', 'From your account, under Referrals.'],
                ['Get ' . $target . ' paid tickets',
                 'A ticket counts once it’s paid for. Refunds don’t count.'],
            ],
            default => [],
        };

        $out = [];
        foreach ($raw as $i => $s) {
            $out[] = ['n' => (string) ($i + 1), 't' => $s[0], 's' => $s[1]];
        }

        return $out;
    }

    // ══════════════════════════════════════════════════════════════════════════
    // What counts
    // ══════════════════════════════════════════════════════════════════════════

    /**
     * Base rules + per-action rules + the mode's ordering rule + the admin's own.
     *
     * **The base can never be removed.** The handoff: "Admins may append rules; they
     * can never remove the generated base." A challenge whose page does not say the
     * phone must be verified, or that one person gets one entry, is a challenge whose
     * published terms do not match the code enforcing them — and the code is what
     * decides who gets paid.
     *
     * @return list<string>
     */
    private static function rules(array $c, string $u): array
    {
        $target = (int) ($c['target'] ?? 1);

        $base = [
            'Your account’s phone number is verified',
            'One entry per person and per phone number',
        ];

        $per = match ((string) ($c['action'] ?? E::ACTION_NOMINATE)) {
            E::ACTION_NOMINATE => [
                $target . ' different people, none of them you',
                'Every field is complete: full name, phone, email, category and a reason of at least 40 characters',
                'Each nominee confirms by SMS or WhatsApp that they are real and agree to be nominated',
                'Our team checks each nomination. Fake or copied details disqualify the whole entry',
            ],
            E::ACTION_REFER => [
                'Tickets bought through your link or code',
                'Paid, not reserved. Refunded tickets are removed',
                'Buying tickets for yourself through your own link doesn’t count',
            ],
            default => [],
        };

        $order = match ((string) ($c['mode'] ?? E::MODE_FIRST)) {
            E::MODE_TOP  => 'Ranked by verified count at the close. Ties go to whoever reached the count first',
            E::MODE_DRAW => 'The draw is recorded and published on ' . self::drawDate($c),
            default      => 'Prizes go in the order entries are fully verified, not the order they were sent',
        };

        // Appended, never substituted — and trimmed of empties, so an admin pressing
        // "add a rule" and leaving it blank does not publish a bullet with no sentence.
        $extra = [];
        foreach (self::listOf($c['extra_rules'] ?? null) as $line) {
            $line = trim((string) $line);
            if ($line !== '') $extra[] = $line;
        }

        return array_merge($base, $per, [$order], $extra);
    }

    // ══════════════════════════════════════════════════════════════════════════
    // The meter, the clock and the one control
    // ══════════════════════════════════════════════════════════════════════════

    private static function meterTitle(array $c, bool $capped, bool $full, int $claimed): string
    {
        $cap = (int) ($c['cap'] ?? 0);

        if (!$capped) {
            return (string) ($c['mode'] ?? '') === E::MODE_TOP
                ? 'Top ' . $cap . ' win'
                : (int) ($c['draw_count'] ?? 0) . ' winners drawn ' . self::drawDate($c);
        }

        return $full
            ? 'All ' . $cap . ' prizes claimed'
            : ($cap - $claimed) . ' of ' . $cap . ' prizes left';
    }

    private static function timeLeft(array $c, bool $upcoming, bool $ended, bool $full, int $days): string
    {
        if ($upcoming) {
            $s = trim((string) ($c['starts'] ?? ''));
            // The DC hardcodes "Starts 5 Oct". Without a date to read, the honest
            // answer is the one that cannot go stale.
            return $s !== '' ? 'Starts ' . explode(',', $s)[0] : 'Starts soon';
        }
        if ($ended) return 'Closed';
        if ($full)  return 'Challenge full';

        // "1 days left" is the sentence that makes a countdown look automated, and the
        // last day is the one most people read it on.
        if ($days <= 0) return 'Closes today';

        return $days === 1 ? '1 day left' : $days . ' days left';
    }

    private static function cta(string $action, bool $upcoming, bool $ended, bool $full, bool $joined): string
    {
        if ($upcoming) return 'Remind me';
        if ($ended)    return 'See the results';
        if ($full)     return 'See the awards';
        if ($joined)   return $action === E::ACTION_REFER ? 'Get my link' : 'Add a nominee';

        return 'Sign in to join';
    }

    /**
     * Where the one control goes.
     *
     * The DC points these at its sibling comps (`AwardsPage.dc.html`, `SignIn.dc.html`);
     * they are this site's own routes here. A signed-out visitor is returned to the
     * challenge afterwards rather than dropped on their account — somebody who pressed
     * "Sign in to join" is mid-task, and a sign-in that forgets what it interrupted is
     * how a person gives up at the last step.
     */
    private static function ctaHref(
        string $action, bool $upcoming, bool $ended, bool $full, bool $joined, array $c,
    ): string {
        $slug = (string) ($c['slug'] ?? '');

        if ($upcoming) return '/challenges/' . $slug . '#remind';
        if ($ended || $full) return '/awards';
        if ($joined) return $action === E::ACTION_REFER ? '/account#me-referral' : '/nominate';

        return '/account/login?next=' . rawurlencode('/challenges/' . $slug);
    }

    private static function ctaNote(int $cap, bool $upcoming, bool $ended, bool $full, bool $joined): string
    {
        if ($upcoming) return 'We’ll send one SMS when it opens.';
        if ($ended)    return 'Thanks to everyone who took part.';
        // Said because it is true and because it is the thing somebody who just missed
        // out needs to hear: the work they already did still counts for the award.
        if ($full)     return 'All ' . $cap . ' prizes are taken. Your nominations still count for the awards.';
        if ($joined)   return 'Track your progress in your account.';

        return 'Free to join. You need an account with a verified phone number.';
    }

    /** The one line under the prize on the phone's fixed bottom bar. */
    private static function barSub(
        int $cap, int $claimed, int $days, bool $full, bool $joined, bool $capped, string $mine,
    ): string {
        if ($full)   return 'All claimed';
        if ($joined) return $mine;

        $left = $days <= 0 ? 'closes today' : ($days === 1 ? '1 day' : $days . ' days');

        return $capped
            ? ($cap - $claimed) . ' of ' . $cap . ' left · ' . $left
            : ($days <= 0 ? 'Closes today' : ($days === 1 ? '1 day left' : $days . ' days left'));
    }

    /**
     * The four questions, with the payout answer following the prize type.
     *
     * @return list<array{q:string,a:string}>
     */
    private static function faq(array $c): array
    {
        $paid = match ((string) ($c['prize_type'] ?? E::PRIZE_CASH_EACH)) {
            E::PRIZE_POINTS  => 'Points land in your account within a day of the close and can be redeemed for votes.',
            E::PRIZE_TICKETS => 'Tickets are sent to your account and by SMS within a day of the draw.',
            default          => 'Within 7 days of qualifying, to the mobile money wallet or bank account in your name.',
        };

        return [
            ['q' => 'Who can take part?',
             'a' => 'Anyone with an Africa GATES account and a verified phone number. One entry per person.'],
            ['q' => 'How is the prize paid?', 'a' => $paid],
            ['q' => 'Can I change an entry?',
             'a' => 'You can edit anything until it’s verified. After that it’s locked, so check the details first.'],
            ['q' => 'What if something looks wrong?',
             'a' => 'Tell us from the challenge page or ask Gee. We review every report before prizes go out.'],
        ];
    }

    // ══════════════════════════════════════════════════════════════════════════

    /** The DC's `n.toLocaleString('en')` — a thousands separator and nothing else. */
    private static function fmt(int $n): string
    {
        return number_format($n);
    }

    /**
     * Days until the close, from the stored date.
     *
     * The DC reads `c.days` off its fixture. A number of days typed onto a row is right
     * the day it is saved and wrong every day after, on a page that prints it as a
     * promise — so the column is read where there is one, and the fixture's own `days`
     * is the fallback that keeps the three demo configs reproducible.
     */
    private static function daysLeft(array $c, array $ctx): int
    {
        $ends = trim((string) ($c['ends_at'] ?? ''));

        if ($ends !== '') {
            try {
                $now = new \DateTimeImmutable((string) ($ctx['now'] ?? 'now'));
                $end = new \DateTimeImmutable($ends);

                return max(0, (int) $now->diff($end)->format('%r%a'));
            } catch (\Throwable) {
                // An unparseable date is the fixture's problem, not the page's: fall
                // through to the stored figure rather than printing "-1 days left".
            }
        }

        return max(0, (int) ($c['days'] ?? 0));
    }

    /** A draw date an admin has not set yet must not print the word "null". */
    private static function drawDate(array $c): string
    {
        $d = trim((string) ($c['draw_date'] ?? $c['draw_at'] ?? ''));

        return $d !== '' ? $d : 'the closing date';
    }

    /**
     * `extra_rules` as a list, however it was stored.
     *
     * It is JSON in the column and an array in a fixture, and a service that accepts
     * only one of those is a service that works in the suite and not on the row.
     *
     * @return list<mixed>
     */
    private static function listOf(mixed $raw): array
    {
        if (is_array($raw)) return array_values($raw);
        if (!is_string($raw) || trim($raw) === '') return [];

        try {
            $d = json_decode($raw, true, 8, JSON_THROW_ON_ERROR);

            return is_array($d) ? array_values($d) : [];
        } catch (\Throwable) {
            return [];
        }
    }
}
