<?php
declare(strict_types=1);

namespace AfricaGates\Services;

/**
 * The flier's whole palette, computed from the event's own accent, in one of four styles.
 *
 * ══════════════════════════════════════════════════════════════════════════════
 * WHY THE FLIER CANNOT KEEP ITS OWN COLOURS
 * ══════════════════════════════════════════════════════════════════════════════
 *
 * It shipped with eleven hard-coded hexes: a dark green plate, a warm paper, one gold. Every
 * flier for every event came out the same colour, on a platform where an organiser picks an
 * accent and {@see EventTierPalette} already moves the entire ticket ladder to match it. So
 * an organiser could set their event teal, watch the tier chips, the selection light and the
 * printed ticket all follow — and then the thing their attendees actually post to WhatsApp
 * came out green.
 *
 * That is the failure the tier palette's own docblock opens with, one surface further out:
 * "the organiser changes the event's accent colour, and the six tier colours they chose
 * against the old one stay exactly where they were."
 *
 * ══════════════════════════════════════════════════════════════════════════════
 * AND WHY IT DERIVES RATHER THAN STORING
 * ══════════════════════════════════════════════════════════════════════════════
 *
 * Nothing here is stored and nothing is picked. A style is a KEY — `deep`, `paper`, `bold`,
 * `tint` — and every hex is computed from the accent on every read, which is the same reason
 * a tier stores a slot rather than a colour. Change the accent and every flier already shared
 * keeps working while every new one moves. There is no second place for a colour to go stale.
 *
 * `EventTierPalette` is the colour authority and this composes it: its HSL conversion, its
 * `ink()` guarantee, its `contrast()`. Not one line of colour maths is repeated here, because
 * two derivations of one accent is precisely how two surfaces come to disagree about what the
 * event's colour is.
 *
 * ══════════════════════════════════════════════════════════════════════════════
 * EVERY PAIR IS MEASURED, NOT CHOSEN
 * ══════════════════════════════════════════════════════════════════════════════
 *
 * A palette generated by arithmetic will hand you white type on a pale yellow ground the
 * first time somebody picks pale yellow, and it will look fine in every test that only checks
 * an image came back. So each derived colour is walked along its own lightness until it clears
 * a measured ratio against the ground it will actually sit on:
 *
 *   - `ink` and `mute` — 4.5:1 (WCAG 1.4.3, normal text; the meta line is small at phone
 *     scale even though it is 26px in a 1080px image)
 *   - `accent` — 4.5:1 as well, because it carries the kicker, which is the smallest type on
 *     the flier. Not 3:1: that floor is for a graphic, and this one is a word.
 *   - `on_accent` — 4.5:1 against the accent, via EventTierPalette::ink(), which guarantees
 *     it by falling through to pure black rather than approximating with a luminance
 *     threshold.
 *
 * {@see \Tests\Unit\EventFlierThemeTest} asserts those floors by SAMPLING THE ACCENT SPACE
 * rather than by checking the handful of colours anybody had in mind — the same method the
 * tier palette's tests use, and the only one that catches the accent nobody thought of.
 *
 * ══════════════════════════════════════════════════════════════════════════════
 * A MONOCHROME EVENT KEEPS THE HOUSE GOLD
 * ══════════════════════════════════════════════════════════════════════════════
 *
 * Black, white and grey have no hue to build a highlight from, and a grey highlight on a grey
 * ground is not a highlight — it is the ink again, one step darker. `EventTierPalette` answers
 * the same problem by keeping an achromatic ladder achromatic, because inventing hues there
 * would hand an organiser six colours matching nothing on their event.
 *
 * Here the answer inverts, and for a reason: the accent slot on this flier is where the
 * platform's own name is set. The Africa GATES gold is not a colour invented for a grey event
 * — it is the house accent, and on a charcoal flier it reads as branding rather than as a
 * clash. So a monochrome event gets a monochrome ground and a gold accent.
 */
final class EventFlierTheme
{
    /**
     * The four styles, in the order they are offered.
     *
     * Four, and each is a different TREATMENT rather than a different hue — the hue already
     * comes from the event. Six colour variations of one layout is a spectrum, and a spectrum
     * is a decision somebody stops to make; four visibly different designs is a glance.
     *
     * `note` is what the picker prints under the label. It says what the style does, not what
     * it is called: "Dark, cinematic" is choosable, "Deep" alone is not.
     *
     * Two or three words each, measured rather than guessed: at 390px the picker is a
     * two-column grid, and "The event colour, full strength" wrapped to a second line — so
     * that one chip was taller than its neighbours and the grid's rhythm broke on the option
     * most likely to be picked for being loud.
     */
    public const STYLES = [
        'deep'  => ['label' => 'Deep',  'note' => 'Dark, cinematic'],
        'paper' => ['label' => 'Paper', 'note' => 'Light, editorial'],
        'bold'  => ['label' => 'Bold',  'note' => 'Full event colour'],
        'tint'  => ['label' => 'Tint',  'note' => 'Photo, tinted'],
    ];

    /**
     * The style a format opens on.
     *
     * `plain` opens on `paper` because the handoff is specific that the no-photo design is
     * "warm ground, typographic — a different design, not a degraded one", and it is the most
     * common case. The photo formats open dark, which is what a photograph wants behind it.
     *
     * A DEFAULT, not a rule. The style and the format were coupled before this file existed —
     * `$paper = $fmt === 'plain'` — which meant there was no such thing as a dark no-photo
     * flier or a light one with a photo in it, and neither of those is a bad idea.
     */
    public const DEFAULTS = ['story' => 'deep', 'square' => 'deep', 'plain' => 'paper'];

    /** The house accent, for an event whose own colour has no hue. See the class note. */
    public const HOUSE = EventFlierLayout::C_GOLD;

    /** Text contrast floor. WCAG 1.4.3 for normal text — see the class note on why not 3:1. */
    private const TEXT = 4.5;

    /**
     * Non-text contrast floor. WCAG 1.4.11 — a graphic that carries meaning needs 3:1.
     *
     * The hairline rule and the mark chip's fill, and only those. It is a lower floor than the
     * text one on purpose: it is what lets the accent stay recognisably the colour the
     * organiser chose instead of being darkened until it is a different colour.
     */
    private const GRAPHIC = 3.0;

    /**
     * Which styles a format can actually offer.
     *
     * `tint` desaturates and re-colours THE PHOTO, so on a format with no photo slot it is a
     * style that does nothing — an option in a picker that changes nothing when chosen is
     * worse than one that is absent, because the person presses it and concludes the flier is
     * broken.
     *
     * @return array<string, array{label:string, note:string}>
     */
    public static function stylesFor(string $fmt): array
    {
        $all = self::STYLES;
        if (!isset(EventFlierLayout::PHOTO[$fmt])) unset($all['tint']);

        return $all;
    }

    /**
     * Normalise a requested style against a format, falling back to that format's default.
     *
     * Never throws and never returns something the format cannot draw: a hand-written URL
     * asking for `tint` on `plain` gets `paper`, not a half-applied style.
     */
    public static function style(mixed $raw, string $fmt): string
    {
        $v = strtolower(trim((string) $raw));

        return isset(self::stylesFor($fmt)[$v])
            ? $v
            : (self::DEFAULTS[$fmt] ?? 'paper');
    }

    /**
     * The palette for one event in one style.
     *
     * @param object|array|null $event a `gates_site_events` row
     * @return array{style:string, dark:bool, ground_top:string, ground_bot:string, ink:string,
     *               mute:string, accent:string, on_accent:string, chip_fill:string,
     *               chip_ink:string, plate:string, rule:string, qr_plate:string,
     *               qr_ink:string, photo_tint:?string}
     */
    public static function forEvent(object|array|null $event, mixed $style, string $fmt): array
    {
        $e = $event === null ? [] : (is_array($event) ? $event : (array) $event);

        return self::fromAccent(
            EventTicketDesign::colour((string) ($e['ticket_accent'] ?? '')),
            self::style($style, $fmt),
            $fmt
        );
    }

    /**
     * The palette from a bare accent. Every branch below ends in {@see resolve()}, which is
     * what applies the measured floors — so no style can ship an unreadable pair by being
     * written carelessly here.
     *
     * @return array<string,mixed>
     */
    public static function fromAccent(string $accent, string $style, string $fmt = 'plain'): array
    {
        $hex = EventTicketDesign::colour($accent);
        $style = self::style($style, $fmt);
        [$h, $s, $l] = EventTierPalette::toHsl($hex);

        $grey = $s < 0.08;

        // The highlight's HUE. The accent's own, or the house gold's when the event has no
        // hue to lend — see the class note on why that inverts the tier palette's answer.
        [$ah, $as] = $grey
            ? array_slice(EventTierPalette::toHsl(self::HOUSE), 0, 2)
            : [$h, max(0.35, min(0.95, $s))];

        // Saturation working bands. An accent at 4% saturation cannot tint a ground visibly
        // and one at 100% cannot do it without shouting, so the ground's chroma is its own
        // band rather than the accent's — the same reasoning as the tier ladder's working
        // band, which exists because the platform's near-black default would otherwise
        // produce six near-blacks.
        $deepS  = $grey ? 0.0 : max(0.30, min(0.68, $s));
        $paperS = $grey ? 0.0 : max(0.06, min(0.20, $s * 0.34));

        $t = match ($style) {
            // ── DEEP ────────────────────────────────────────────────────────
            // The event's colour taken down to a ground a photograph can sit on. Not the
            // accent darkened by a fixed amount: that is invisible on the platform's own
            // near-black default, which is the accent most events will actually have.
            'deep', 'tint' => [
                'dark'       => true,
                // 0.175/0.085, not 0.135/0.055. At the lower pair a navy event and a plum
                // event produced grounds 29 redmean units apart — near-black either way, so
                // the event's colour survived only in the highlight and the chips, and the
                // ground of the graphic people actually post was effectively black for
                // everybody. Raising it eight points of lightness makes the hue legible while
                // leaving white ink above 13:1, which is nowhere near the floor.
                'ground_top' => EventTierPalette::fromHsl($h, $deepS, 0.175),
                'ground_bot' => EventTierPalette::fromHsl($h, $deepS, 0.085),
                'ink_seed'   => '#FFFFFF',
                'mute_seed'  => EventTierPalette::fromHsl($h, $deepS * 0.55, 0.74),
                'acc_seed'   => EventTierPalette::fromHsl($ah, $as, 0.54),
                'chip_seed'  => '#FFFFFF',
            ],

            // ── PAPER ───────────────────────────────────────────────────────
            // A warm light ground carrying a whisper of the event's hue. The chroma ceiling
            // is low on purpose: paper tinted past about 20% saturation stops reading as
            // paper and starts reading as a coloured card, which is what `bold` is for.
            'paper' => [
                'dark'       => false,
                'ground_top' => EventTierPalette::fromHsl($h, $paperS, 0.955),
                'ground_bot' => EventTierPalette::fromHsl($h, $paperS * 1.25, 0.885),
                'ink_seed'   => EventTierPalette::fromHsl($h, min(0.55, $s * 0.6), 0.10),
                'mute_seed'  => EventTierPalette::fromHsl($h, min(0.40, $s * 0.5), 0.40),
                'acc_seed'   => EventTierPalette::fromHsl($ah, $as, 0.42),
                'chip_seed'  => EventTierPalette::fromHsl($h, $paperS, 0.985),
            ],

            // ── BOLD ────────────────────────────────────────────────────────
            // The ground IS the accent, at full chroma — and at a lightness pushed OUT OF THE
            // MIDDLE, which is the part that had to be measured rather than reasoned about.
            //
            // A mid-lightness saturated ground (a #237b22 green, a #1d6fa5 blue) is the worst
            // case in the whole space: nothing but near-white clears 4.5:1 on it, so `ink` and
            // `mute` both got pushed to white and the flier lost its hierarchy entirely — one
            // colour for the name, the title and the date. Sampling the accent space is what
            // showed that; the first version looked correct on every accent anybody would
            // have picked by hand.
            //
            // So the lightness lands in one of two bands and never between them. Full chroma
            // is what "bold" promises and it is kept; the lightness is not part of that
            // promise, and 0.28 of a saturated hue still reads unmistakably as that hue.
            default => (static function () use ($h, $s, $l, $as, $grey): array {
                [$gTop, $gBot, $seed, $dark] = self::band($h, $s, $l);

                return [
                    'dark'       => $dark,
                    'ground_top' => $gTop,
                    'ground_bot' => $gBot,
                    'ink_seed'   => $seed,
                    // A TINTED mute rather than the ink again. On a saturated ground the two
                    // can only separate along lightness, and there is no room — so it
                    // separates along chroma instead: a pale (or deep) tint of the ground's
                    // own hue, which is both tellable from the ink and still in the family.
                    'mute_seed'  => $dark
                        ? EventTierPalette::fromHsl($h, $grey ? 0.0 : 0.22, 0.90)
                        : EventTierPalette::fromHsl($h, $grey ? 0.0 : 0.32, 0.18),
                    // The highlight cannot be the accent — the accent is the ground. It comes
                    // from the tier palette's own `bold` slot: 152° round the wheel,
                    // deliberately NOT the 180° complement, because that is "the one
                    // relationship that stops reading as the same family and starts reading as
                    // a clash". The same rotation, from the same file, for the same reason.
                    'acc_seed'   => $grey
                        ? self::HOUSE
                        : EventTierPalette::fromHsl(EventTierPalette::hue($h + 152), $as * 0.9,
                                                    $dark ? 0.62 : 0.34),
                    'chip_seed'  => $seed,
                ];
            })(),
        };

        return self::resolve($t, $style, $fmt, $h, $as, $ah, $grey);
    }

    /**
     * Apply the measured floors and finish the token set.
     *
     * ── AGAINST WHICH GROUND ─────────────────────────────────────────────────
     *
     * The canvas is a vertical gradient, so every colour has TWO grounds and has to clear the
     * floor on the worse of them. Checking only one is how a `mute` that measured 4.6 at the
     * top of the plate measured 3.9 at the bottom, where half the meta line actually sits —
     * and a gradient is exactly the case where an eyeball says it is fine.
     *
     * @param array<string,mixed> $t
     * @return array<string,mixed>
     */
    private static function resolve(array $t, string $style, string $fmt,
                                    float $h, float $as, float $ah, bool $grey): array
    {
        $top = (string) $t['ground_top'];
        $bot = (string) $t['ground_bot'];

        $ink  = self::lift((string) $t['ink_seed'],  $top, $bot, self::TEXT);
        $mute = self::lift((string) $t['mute_seed'], $top, $bot, self::TEXT);
        $chip = (string) $t['chip_seed'];

        // ── TWO ACCENTS, AND THE SPLIT IS THIS CODEBASE'S OWN ────────────────
        //
        // `EventTierPalette` publishes `fill` and `edge` per swatch for exactly this reason,
        // and CLAUDE.md spells out the distinction: "hue is fill — the identity, the swatch
        // the organiser picked"; "edge is the darker variant, and it is only for things that
        // owe 3:1 against white". Painting the light with `edge` shows the organiser a colour
        // they did not choose.
        //
        // Here it inverts, because the ground is dark as often as it is light: the GRAPHICS
        // want the identity and the TEXT wants whatever clears the reading floor. One value
        // for both is what made a gold event's paper flier come out olive — the accent
        // darkened to 4.5:1 on cream is no longer recognisably the colour anybody chose, and
        // it was being used for the rule and the chip fill as well as for the kicker.
        //
        // So: `accent` is the identity, lifted only as far as WCAG 1.4.11's 3:1 for a
        // non-text indicator, and it is what the hairline rule and the "Ticket confirmed"
        // chip are painted with. `accent_text` clears 4.5:1 and is what the kicker and the
        // invitation are set in. On a dark ground they are usually the same value; on cream
        // they are a gold bar with dark-gold lettering, which is the design rather than a
        // compromise.
        $acc     = self::lift((string) $t['acc_seed'], $top, $bot, self::GRAPHIC);
        $accText = self::lift($acc, $top, $bot, self::TEXT);

        // ── MUTE HAS TO BE TELLABLE FROM INK ────────────────────────────────
        //
        // Both are pushed toward the same end of the range by the contrast floor, so on a
        // mid-lightness ground they can converge — and a "muted" line the same colour as the
        // primary one is not a hierarchy, it is two lines that look like a mistake. Pulled
        // back toward the ground until it separates, but never past the floor: `lift()` is
        // asked again after every step, so legibility wins over hierarchy if it has to.
        $mute = self::separateFrom($mute, $ink, $top, $bot);

        return [
            'style'      => $style,
            'dark'       => (bool) $t['dark'],
            'ground_top' => $top,
            'ground_bot' => $bot,
            'ink'        => $ink,
            'mute'       => $mute,
            'accent'      => $acc,
            'accent_text' => $accText,
            // Guaranteed against the accent by EventTierPalette, which falls through to pure
            // black rather than approximating — this is the text inside the "Ticket
            // confirmed" chip, on a fill an organiser chose.
            'on_accent'  => EventTierPalette::ink($acc),
            'chip_fill'  => $chip,
            'chip_ink'   => EventTierPalette::ink($chip),
            // What the photo fades into, and it is the GROUND rather than a fixed dark green.
            // A paper-style flier with a photo used to fade that photo into #0d2f26 under
            // light type: a dark band across the middle of a light graphic, which reads as a
            // rendering fault because that is what it is.
            'plate'      => $top,
            'rule'       => $acc,

            // ── THE QR IS NOT THEMED, AND THAT IS DELIBERATE ─────────────────
            //
            // A symbol needs dark modules on a light field: that is the specification, not a
            // preference, and a reader that copes with an inverted or low-contrast symbol is
            // a reader somebody happens to have. Every other pixel on this flier follows the
            // event; these two do not follow anything, because a code that scans is worth
            // more than a code that matches. The 4-module quiet zone is the same kind of
            // rule — see EventFlierLayout::QR.
            'qr_plate'   => '#FFFFFF',
            'qr_ink'     => '#000000',

            // ── AND THE PHOTO TINT ───────────────────────────────────────────
            //
            // Only `tint`, and only where there is a photo slot to apply it to. A mid-lightness
            // member of the accent's family rather than the accent itself: colorize() shifts
            // channels by a signed offset from mid-grey, so a near-black accent would map the
            // whole photograph to near-black and a pastel would wash it to nothing.
            'photo_tint' => ($style === 'tint' && isset(EventFlierLayout::PHOTO[$fmt]))
                ? EventTierPalette::fromHsl($ah, $grey ? 0.0 : max(0.30, min(0.72, $as)), 0.52)
                : null,
        ];
    }

    /**
     * Headroom the `bold` ground is built to leave its ink. Above the 4.5 floor on purpose:
     * `mute` has to fit under the ink as well, and a ground that only just clears the floor
     * leaves nowhere for a second value to go — which is how `bold` came to draw the name, the
     * title and the date in one colour.
     */
    private const BAND_TARGET = 6.5;

    /**
     * The `bold` ground: the accent at full chroma, at a lightness that can carry type.
     *
     * ══════════════════════════════════════════════════════════════════════════
     * WHY THIS IS MEASURED AND NOT BANDED BY HSL LIGHTNESS
     * ══════════════════════════════════════════════════════════════════════════
     *
     * The first version split on `$l >= 0.5` and pushed into a fixed light or dark band. That
     * is wrong for blue and it is wrong in the direction that matters: HSL lightness overstates
     * how light a saturated blue looks, so pure `#0000ff` — an `$l` of exactly 0.50 — went into
     * the LIGHT band, and the resulting ground gave its best available ink 3.5:1. Under the
     * floor, on a primary colour, from a rule that reads as obviously correct.
     *
     * So the direction is chosen by MEASURING which ink is more legible on the accent as given,
     * and the walk continues until one ink clears {@see BAND_TARGET} at **both** ends of the
     * gradient. Both ends, and the same ink at each: a gradient is exactly the case where two
     * separately-checked ends each look fine and the type crossing them does not.
     *
     * Full chroma is what "bold" promises and it is never touched. The lightness is not part of
     * that promise, and 0.2 of a saturated hue still reads unmistakably as that hue.
     *
     * @return array{0:string,1:string,2:string,3:bool} ground top, ground bottom, ink seed, dark
     */
    private static function band(float $h, float $s, float $l): array
    {
        $at = static fn (float $x): string => EventTierPalette::fromHsl($h, $s, max(0.02, min(0.98, $x)));

        // Which way is safe. Not a lightness comparison — the luminance one, which is the
        // question actually being asked: is black more readable on this colour, or white.
        $seedHex = $at($l);
        $up = EventTierPalette::contrast('#000000', $seedHex)
            > EventTierPalette::contrast('#FFFFFF', $seedHex);

        // The gradient's span, in lightness. Small: the gradient is there so a flat field of
        // one colour has some depth in it, not to travel.
        $span = 0.06;

        $bestPair  = null;
        $bestWorst = -INF;

        for ($i = 0; $i <= 26; $i++) {
            $step = $up ? $l + $i * 0.028 : $l - $i * 0.028;
            $safe = $at($step);
            $near = $at($up ? $step - $span : $step + $span);

            // ONE ink, decided on the end it has the harder time on, then checked on both.
            $ink   = $up ? '#000000' : '#FFFFFF';
            $worst = min(EventTierPalette::contrast($ink, $safe),
                         EventTierPalette::contrast($ink, $near));

            // Top is always the lighter of the two, whichever direction the walk went, so the
            // gradient reads the way every other ground on this flier does.
            $pair = $up ? [$safe, $near] : [$near, $safe];

            if ($worst > $bestWorst) { $bestWorst = $worst; $bestPair = $pair; }
            if ($worst >= self::BAND_TARGET) break;
        }

        [$top, $bot] = $bestPair ?? [$at($l), $at($l)];

        // The seed comes from EventTierPalette::ink() on the harder end rather than from the
        // `$up` guess, so it inherits that function's guarantee — it falls through to pure
        // black rather than approximating with a luminance threshold.
        $seed = EventTierPalette::ink($up ? $bot : $top);

        // `dark` means "light type on this ground", which is exactly "the ink is white".
        return [$top, $bot, $seed, $seed === '#FFFFFF'];
    }

    /**
     * Walk a colour along its own lightness until it clears $target against BOTH grounds.
     *
     * Away from the grounds, so it gets more legible rather than less: a light ground pushes
     * the colour darker and a dark ground pushes it lighter, decided by measuring the ground
     * rather than by trusting the style's own `dark` flag — on `bold` that flag is itself
     * derived from the accent and can be either.
     *
     * Returns the best it reached if the target is unreachable, which happens only for a
     * ground at the very end of the range. Never returns the seed unchanged in that case:
     * the best available is still better than the thing that failed.
     */
    private static function lift(string $seed, string $top, string $bot, float $target): string
    {
        $worst = static fn (string $hex): float => min(
            EventTierPalette::contrast($hex, $top),
            EventTierPalette::contrast($hex, $bot));

        if ($worst($seed) >= $target) return $seed;

        // Which way is away. Measured against the darker of the two grounds, since that is
        // the one a light colour has to clear and a dark colour has to escape.
        $groundLighter = EventTierPalette::contrast('#FFFFFF', $bot)
                       < EventTierPalette::contrast('#000000', $bot);

        [$h, $s, $l] = EventTierPalette::toHsl($seed);
        $best     = $seed;
        $bestSeen = $worst($seed);

        for ($i = 1; $i <= 24; $i++) {
            $cl = $groundLighter ? max(0.0, $l - $i * 0.04) : min(1.0, $l + $i * 0.04);
            $hex = EventTierPalette::fromHsl($h, $s, $cl);
            $got = $worst($hex);

            if ($got > $bestSeen) { $bestSeen = $got; $best = $hex; }
            if ($got >= $target) return $hex;
        }

        return $best;
    }

    /** How far two colours have to sit apart to read as a hierarchy. Redmean, 0–765. */
    private const MUTE_GAP = 58.0;

    /**
     * Pull $mute back toward the ground until it is tellable from $ink, without dropping
     * below the text floor. Legibility wins: a muted line that is merely close to the ink is
     * a cosmetic problem, and one nobody can read is not.
     */
    private static function separateFrom(string $mute, string $ink, string $top, string $bot): string
    {
        if (EventTierPalette::distance($mute, $ink) >= self::MUTE_GAP) return $mute;

        $worst = static fn (string $hex): float => min(
            EventTierPalette::contrast($hex, $top),
            EventTierPalette::contrast($hex, $bot));

        // Toward the ground is the direction that reduces contrast, so each step is checked
        // against the floor before it is accepted.
        $inkLight = EventTierPalette::contrast($ink, '#000000')
                  > EventTierPalette::contrast($ink, '#FFFFFF');

        [$h, $s, $l] = EventTierPalette::toHsl($mute);
        $best = $mute;

        for ($i = 1; $i <= 14; $i++) {
            $cl = $inkLight ? max(0.0, $l - $i * 0.035) : min(1.0, $l + $i * 0.035);
            $hex = EventTierPalette::fromHsl($h, $s, $cl);
            if ($worst($hex) < self::TEXT) break;

            $best = $hex;
            if (EventTierPalette::distance($hex, $ink) >= self::MUTE_GAP) return $hex;
        }

        return $best;
    }

    /**
     * What the style picker draws: label, note, and the three colours a chip needs.
     *
     * The swatches are the REAL palette for THIS event, computed here rather than written into
     * the template as approximations. A picker showing a generic dark-green chip beside a
     * flier that comes out teal is a control that lies about its own outcome, and the whole
     * point of this feature is that the flier takes the organiser's colour.
     *
     * @return list<array{key:string, label:string, note:string, ground:string, ink:string, accent:string}>
     */
    public static function swatches(object|array|null $event, string $fmt): array
    {
        $out = [];
        foreach (array_keys(self::stylesFor($fmt)) as $key) {
            $t = self::forEvent($event, $key, $fmt);
            $out[] = [
                'key'    => $key,
                'label'  => self::STYLES[$key]['label'],
                'note'   => self::STYLES[$key]['note'],
                'ground' => $t['ground_bot'],
                'ink'    => $t['ink'],
                'accent' => $t['accent'],
            ];
        }
        return $out;
    }
}
