<?php
declare(strict_types=1);

namespace AfricaGates\Services;

use AfricaGates\Support\Env;
use Illuminate\Database\Capsule\Manager as DB;
use Illuminate\Support\Carbon;

/**
 * Single-use, gated form links for verified nominees and invited judges.
 *
 * A token is a capability: it is e-mailed to the subject, can be opened and
 * submitted exactly ONCE, expires, and can be regenerated by an admin (which
 * invalidates any earlier unused token for that subject). The submitted payload
 * is stored for the record and best-effort applied to the subject.
 *
 * Static + DB-backed so any controller/cron can issue or consume a token
 * without DI plumbing (mirrors WebhookService / PointsService).
 */
class GatedFormService
{
    public const PURPOSES = ['nominee', 'judge'];

    /**
     * Issue a fresh single-use token for a subject, invalidating any earlier
     * UNUSED token for the same (purpose, subject). Returns the raw token (the
     * only time it exists in clear — only its SHA-256 hash is stored).
     */
    public static function issue(string $purpose, int $subjectId, string $email = '', int $ttlDays = 30): string
    {
        if (!in_array($purpose, self::PURPOSES, true) || $subjectId < 1) {
            throw new \InvalidArgumentException('Invalid gated-form subject.');
        }
        DB::table('gates_form_tokens')->where('purpose', $purpose)->where('subject_id', $subjectId)->where('is_used', 0)->delete();
        $raw = bin2hex(random_bytes(20)); // 40-char URL-safe token
        DB::table('gates_form_tokens')->insert([
            'purpose'    => $purpose,
            'subject_id' => $subjectId,
            'email_hash' => $email !== '' ? hash('sha256', strtolower(trim($email))) : null,
            'token_hash' => hash('sha256', $raw),
            'is_used'    => 0,
            'expires_at' => Carbon::now()->addDays(max(1, $ttlDays))->toDateTimeString(),
            'created_at' => Carbon::now()->toDateTimeString(),
        ]);
        return $raw;
    }

    /** Full link for a raw token (uses APP_URL). */
    public static function link(string $raw): string
    {
        $base = rtrim((string) Env::get('APP_URL', 'https://afg.afrovanguard.org.ng'), '/');
        return $base . '/form/' . $raw;
    }

    /** Look up a token row by its raw value (or null). */
    public static function resolve(string $raw): ?object
    {
        $raw = trim($raw);
        if ($raw === '') return null;
        return DB::table('gates_form_tokens')->where('token_hash', hash('sha256', $raw))->first() ?: null;
    }

    /** 'ok' | 'used' | 'expired' | 'invalid' for a resolved row. */
    public static function status(?object $row): string
    {
        if (!$row) return 'invalid';
        if ((int) $row->is_used === 1) return 'used';
        if ($row->expires_at && $row->expires_at < Carbon::now()->toDateTimeString()) return 'expired';
        return 'ok';
    }

    /**
     * Consume a token: store the payload, mark it used (single-use), and apply
     * the data to the subject. Returns ['ok'=>bool, 'status'=>..., 'purpose'=>...].
     */
    public static function submit(string $raw, array $data): array
    {
        $row = self::resolve($raw);
        $status = self::status($row);
        if ($status !== 'ok') return ['ok' => false, 'status' => $status];

        // Atomic single-use claim: re-assert is_used = 0 in the UPDATE so only the
        // caller that actually flips 0→1 proceeds. A concurrent double-submit (or a
        // deliberate parallel replay) affects 0 rows and loses the race.
        $claimed = DB::table('gates_form_tokens')
            ->where('id', $row->id)->where('is_used', 0)
            ->update([
                'payload' => json_encode($data, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
                'is_used' => 1,
                'used_at' => Carbon::now()->toDateTimeString(),
            ]);
        if ($claimed === 0) return ['ok' => false, 'status' => 'used'];

        try { self::applyToSubject((string) $row->purpose, (int) $row->subject_id, $data); } catch (\Throwable $e) {}
        return ['ok' => true, 'status' => 'ok', 'purpose' => (string) $row->purpose];
    }

    /** Best-effort enrichment of the subject from the submitted form (never throws to the caller). */
    private static function applyToSubject(string $purpose, int $id, array $data): void
    {
        $bio = mb_substr(trim((string) ($data['bio'] ?? '')), 0, 2000);
        $schema = DB::getSchemaBuilder();

        if ($purpose === 'nominee') {
            if ($bio !== '') DB::table('gates_nominees')->where('id', $id)->update(['tagline' => mb_substr($bio, 0, 200)]);
            $pid = (int) (DB::table('gates_nominees')->where('id', $id)->value('profile_id') ?? 0);
            if ($pid > 0 && $bio !== '' && $schema->hasColumn('gates_profiles', 'bio')) {
                DB::table('gates_profiles')->where('id', $pid)->update(['bio' => $bio]);
            }
        } elseif ($purpose === 'judge') {
            $upd = [];
            if ($bio !== '' && $schema->hasColumn('gates_judges', 'bio')) $upd['bio'] = $bio;
            $expertise = mb_substr(trim((string) ($data['expertise'] ?? '')), 0, 200);
            if ($expertise !== '' && $schema->hasColumn('gates_judges', 'expertise')) $upd['expertise'] = $expertise;
            if ($upd) DB::table('gates_judges')->where('id', $id)->update($upd);
        }
    }

    /** Subject display name for the form header (or '' when not found). */
    public static function subjectName(string $purpose, int $id): string
    {
        try {
            if ($purpose === 'nominee') return (string) (DB::table('gates_nominees')->where('id', $id)->value('name') ?? '');
            if ($purpose === 'judge')   return (string) (DB::table('gates_judges')->where('id', $id)->value('name') ?? '');
        } catch (\Throwable $e) {}
        return '';
    }

    /** Terms URL for the subject — the nominee's programme terms, else the general terms. */
    public static function subjectTermsUrl(string $purpose, int $id): string
    {
        try {
            if ($purpose === 'nominee') {
                $slug = DB::table('gates_nominees as n')
                    ->join('gates_award_categories as c', 'c.id', '=', 'n.category_id')
                    ->join('gates_award_cycles as cy', 'cy.id', '=', 'c.cycle_id')
                    ->join('gates_award_programmes as p', 'p.id', '=', 'cy.programme_id')
                    ->where('n.id', $id)->value('p.slug');
                if ($slug) return '/terms/' . $slug;
            }
        } catch (\Throwable $e) {}
        return '/terms';
    }
}
