import json, subprocess, sys, numpy as np, cv2

# One payload per version boundary, both sides, plus the real flier shapes. Every vector is
# DECODED before it is written: a golden file that only records what the encoder already does
# is a regression test for a bug as much as for correctness.
cases = []
for n in [1, 11, 12, 20, 21, 32, 33, 46, 47, 60, 61, 74]:
    cases.append('A' * n)
cases += [
    'https://afg.afrovanguard.org.ng/e/gala',
    'https://afg.afrovanguard.org.ng/e/gala?r=AB12CD&c=flier',
    'https://afg.afrovanguard.org.ng/events/africa-gates-gala-2026',
    'https://afg.afrovanguard.org.ng/events/x?ref=aB9-_z&utm_source=flier',
    'https://x.ng/r/aB12', 'Ada Nwosu', 'AFG-EVT-9K2M4Q',
    'mailto:tickets@example.org', "O'Brien-Adeyemi, Ngozi (guest)",
]
open('/tmp/qrcases.json','w').write(json.dumps(cases))
mine = json.loads(subprocess.check_output(['php', sys.argv[1], '/tmp/qrcases.json']).decode())

det = cv2.QRCodeDetector()
out = {}
for t in cases:
    m = mine[t]
    assert m is not None, f'refused: {t!r}'
    n = len(m); S, Q = 8, 4
    side = (n + Q*2) * S
    img = np.full((side, side), 255, np.uint8)
    for r, row in enumerate(m):
        for c, ch in enumerate(row):
            if ch == '1':
                y, x = (r+Q)*S, (c+Q)*S
                img[y:y+S, x:x+S] = 0
    got, _, _ = det.detectAndDecode(img)
    assert got == t, f'decoded {got!r} for {t!r}'
    out[t] = m

json.dump({'_note': 'Generated by tests/Support/qr-bytes-vectors.py; every matrix was decoded '
                    'by OpenCV before being written. Do not hand-edit.',
           'vectors': out},
          open(sys.argv[2], 'w'), indent=0)
print(f'{len(out)} vectors, all decoded')
