<?php
declare(strict_types=1);

namespace Tests\Unit;

use AfricaGates\Controllers\InterviewBotController;
use AfricaGates\Services\AttendeeBot;
use Tests\TestCase;

/**
 * What is actually sent to Attendee, and what is actually accepted back.
 *
 * ══════════════════════════════════════════════════════════════════════════════
 * THE BUG THAT NO TEST COULD SEE
 * ══════════════════════════════════════════════════════════════════════════════
 *
 * {@see AttendeeBot} sent a `webhook_url` field for its whole life. Attendee has no
 * such field — it takes `webhooks`, a list of `{url, triggers}` — and DRF discards
 * unrecognised keys from a request body without complaining. So every create-bot call
 * returned 200, a bot arrived, and no callback was ever registered. 'auto' mode ran on
 * the polling path the entire time.
 *
 * Nothing failed, which is why nothing caught it. The only defence against that class
 * of bug is asserting on the request body itself, which is what the first half of this
 * file does.
 *
 * ══════════════════════════════════════════════════════════════════════════════
 * AND THE HEADER THAT WAS NEVER COMING
 * ══════════════════════════════════════════════════════════════════════════════
 *
 * {@see InterviewBotController} expected an `X-Attendee-Secret` header carrying a value
 * this platform generated. Attendee cannot send that: its per-bot webhooks accept a url
 * and a trigger list and nothing else, no custom headers. It signs instead, with
 * `X-Webhook-Signature` over a canonical re-serialisation of the payload.
 *
 * So the second half pins cross-language compatibility with FIXTURES GENERATED BY
 * PYTHON, using the same algorithm as bots/webhook_utils.py. Signing in PHP and
 * verifying in PHP would prove only that this file agrees with itself; these signatures
 * came from the other side of the wire.
 *
 * The float case is a known, deliberate limit rather than an oversight — Python writes
 * 1.0 where PHP writes 1, so a payload carrying a float fails the check. It is asserted
 * here so the limit is visible and cannot regress into a surprise. Rejecting costs the
 * latency this callback exists to save; the cron re-fetches the same transcript.
 */
final class AttendeeBotRequestTest extends TestCase
{
    /** Raw bytes: "attendee-webhook-secret-fixture-32b", as the dashboard would show it. */
    private const SECRET = 'YXR0ZW5kZWUtd2ViaG9vay1zZWNyZXQtZml4dHVyZS0zMmI=';

    private string $pngPath = '';
    private string $badPath = '';

    protected function setUp(): void
    {
        parent::setUp();
        $_ENV['ATTENDEE_API_KEY']  = 'test-key';
        $_ENV['ATTENDEE_BASE_URL'] = 'https://meetbot.example.org';
        $_ENV['ATTENDEE_BOT_NAME'] = 'Africa GATES Interview Assistant';
        // Off by default here so body assertions are about the field under test.
        $_ENV['ATTENDEE_JOIN_NOTICE'] = 'none';
        unset($_ENV['ATTENDEE_BOT_IMAGE'], $_ENV['OPENAI_API_KEY']);
    }

    protected function tearDown(): void
    {
        foreach ([$this->pngPath, $this->badPath] as $f) {
            if ($f !== '' && is_file($f)) @unlink($f);
        }
        unset(
            $_ENV['ATTENDEE_API_KEY'], $_ENV['ATTENDEE_BASE_URL'], $_ENV['ATTENDEE_BOT_NAME'],
            $_ENV['ATTENDEE_JOIN_NOTICE'], $_ENV['ATTENDEE_BOT_IMAGE']
        );
        parent::tearDown();
    }

    // ── the request body ─────────────────────────────────────────────────────

    public function test_the_body_never_carries_the_field_attendee_does_not_have(): void
    {
        $body = AttendeeBot::buildCreateBody('https://meet.google.com/abc-defg-hij', [
            'webhook_url' => 'https://africagates.example/api/v1/interview/bot/webhook',
        ]);

        $this->assertArrayNotHasKey('webhook_url', $body, 'webhook_url is not an Attendee field and is silently dropped');
        $this->assertSame('https://meet.google.com/abc-defg-hij', $body['meeting_url']);
        $this->assertNotSame('', trim((string) $body['bot_name']));
    }

    public function test_an_https_callback_becomes_a_webhooks_subscription(): void
    {
        $url  = 'https://africagates.example/api/v1/interview/bot/webhook';
        $body = AttendeeBot::buildCreateBody('https://meet.google.com/x', ['webhook_url' => $url]);

        $this->assertSame($url, $body['webhooks'][0]['url']);
        $this->assertContains('bot.state_change', $body['webhooks'][0]['triggers']);
        $this->assertContains('transcript.update', $body['webhooks'][0]['triggers']);
    }

    public function test_it_subscribes_only_to_triggers_this_platform_handles(): void
    {
        $body = AttendeeBot::buildCreateBody('https://meet.google.com/x', [
            'webhook_url' => 'https://africagates.example/hook',
        ]);

        // Chat and participant traffic would wake an endpoint with no handler for it,
        // and each delivery is retried three times on the resulting failure.
        $this->assertNotContains('chat_messages.update', $body['webhooks'][0]['triggers']);
        $this->assertNotContains('participant_events.join_leave', $body['webhooks'][0]['triggers']);
    }

    public function test_a_plain_http_callback_is_dropped_rather_than_breaking_the_bot(): void
    {
        // Attendee's schema pins ^https:// and rejects the whole create call. Passing an
        // http url through would trade a slow transcript for a sitting with no bot.
        $body = AttendeeBot::buildCreateBody('https://meet.google.com/x', [
            'webhook_url' => 'http://insecure.example/hook',
        ]);

        $this->assertArrayNotHasKey('webhooks', $body);
        $this->assertArrayNotHasKey('webhook_url', $body);
    }

    public function test_metadata_is_coerced_to_what_attendee_accepts(): void
    {
        $body = AttendeeBot::buildCreateBody('https://meet.google.com/x', [
            'metadata' => [
                'ag_interview_id' => 42,          // int → string
                'flagged'         => true,        // bool → 'true'
                'nested'          => ['nope'],    // dropped: not a scalar
                'blank'           => '',          // dropped: empty
                ''                => 'no key',    // dropped: no key
            ],
        ]);

        $this->assertSame('42', $body['metadata']['ag_interview_id']);
        $this->assertSame('true', $body['metadata']['flagged']);
        $this->assertArrayNotHasKey('nested', $body['metadata']);
        $this->assertArrayNotHasKey('blank', $body['metadata']);
        $this->assertArrayNotHasKey('', $body['metadata']);
    }

    public function test_an_over_long_metadata_value_is_truncated_not_sent_whole(): void
    {
        // An oversized value fails the create call, which loses a bot over bookkeeping.
        $body = AttendeeBot::buildCreateBody('https://meet.google.com/x', [
            'metadata' => ['note' => str_repeat('x', 5000)],
        ]);

        $this->assertLessThanOrEqual(900, mb_strlen($body['metadata']['note']));
    }

    public function test_the_dedup_key_is_passed_through_when_given(): void
    {
        $body = AttendeeBot::buildCreateBody('https://meet.google.com/x', ['dedup' => 'ag-interview-42']);
        $this->assertSame('ag-interview-42', $body['deduplication_key']);

        $body = AttendeeBot::buildCreateBody('https://meet.google.com/x');
        $this->assertArrayNotHasKey('deduplication_key', $body, 'no key means no constraint');
    }

    // ── the in-meeting announcement ──────────────────────────────────────────

    public function test_none_is_the_off_switch_and_blank_is_not(): void
    {
        $_ENV['ATTENDEE_JOIN_NOTICE'] = 'none';
        $this->assertSame('', AttendeeBot::joinNotice());

        $_ENV['ATTENDEE_JOIN_NOTICE'] = 'NONE';
        $this->assertSame('', AttendeeBot::joinNotice(), 'the sentinel is case-insensitive');

        // Blank reads as unset through Env::get, so it gets the default. This is
        // asserted rather than fixed because the alternative is a special case in Env.
        $_ENV['ATTENDEE_JOIN_NOTICE'] = '';
        $this->assertNotSame('', AttendeeBot::joinNotice());
    }

    public function test_the_notice_becomes_a_chat_message_to_everyone(): void
    {
        $_ENV['ATTENDEE_JOIN_NOTICE'] = 'This interview is being recorded.';
        $body = AttendeeBot::buildCreateBody('https://meet.google.com/x');

        $this->assertSame('everyone', $body['bot_chat_message']['to']);
        $this->assertSame('This interview is being recorded.', $body['bot_chat_message']['message']);
    }

    public function test_emoji_are_stripped_without_leaving_the_gap_behind(): void
    {
        // Attendee's chat endpoint rejects emoji outright, so losing the announcement
        // over a decoration would be a poor trade.
        $_ENV['ATTENDEE_JOIN_NOTICE'] = 'Recorded 🎙️ for the panel';
        $this->assertSame('Recorded for the panel', AttendeeBot::joinNotice());
    }

    // ── the avatar ───────────────────────────────────────────────────────────

    public function test_a_real_png_is_accepted_and_attached(): void
    {
        $this->pngPath = sys_get_temp_dir() . '/ag-avatar-' . getmypid() . '.png';
        file_put_contents($this->pngPath, base64_decode(
            'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8DwHwAFAAH/q842iQAAAABJRU5ErkJggg=='
        ));
        $_ENV['ATTENDEE_BOT_IMAGE'] = $this->pngPath;

        $img = AttendeeBot::botImage();
        $this->assertSame('image/png', $img['type']);
        $this->assertNotFalse(base64_decode($img['data'], true));

        $body = AttendeeBot::buildCreateBody('https://meet.google.com/x');
        $this->assertArrayHasKey('bot_image', $body);
    }

    public function test_an_svg_renamed_png_is_rejected_on_its_bytes(): void
    {
        // Attendee validates the image itself; a mislabelled file fails the create call
        // and the sitting gets no bot — a cosmetic setting taking down the recording.
        $this->badPath = sys_get_temp_dir() . '/ag-avatar-bad-' . getmypid() . '.png';
        file_put_contents($this->badPath, '<svg width="1" height="1"></svg>');
        $_ENV['ATTENDEE_BOT_IMAGE'] = $this->badPath;

        $this->assertNull(AttendeeBot::botImage());
        $this->assertArrayNotHasKey('bot_image', AttendeeBot::buildCreateBody('https://meet.google.com/x'));
    }

    public function test_a_missing_avatar_file_is_simply_no_avatar(): void
    {
        $_ENV['ATTENDEE_BOT_IMAGE'] = sys_get_temp_dir() . '/ag-definitely-absent.png';
        $this->assertNull(AttendeeBot::botImage());
    }

    // ── the callback's signature ─────────────────────────────────────────────

    /**
     * @dataProvider pythonSignedPayloads
     */
    public function test_it_accepts_a_signature_generated_by_attendees_own_algorithm(
        string $wireBody,
        string $signature,
        string $label
    ): void {
        $this->assertTrue(
            $this->verify($wireBody, $signature, self::SECRET),
            "a genuine Attendee delivery was rejected: {$label}"
        );
    }

    /**
     * Bodies exactly as `requests(json=...)` puts them on the wire — spaces after the
     * separators, keys in insertion order — with signatures over the CANONICAL form.
     * The two differ, which is why the raw body cannot simply be hashed.
     *
     * @return list<array{0:string,1:string,2:string}>
     */
    public static function pythonSignedPayloads(): array
    {
        return [
            [
                "{\"idempotency_key\": \"idem-1\", \"bot_id\": \"bot_fixture\", \"trigger\": \"bot.state_change\", \"data\": {\"new_state\": \"ended\", \"old_state\": \"post_processing\"}}",
                'X2/hFFhF1WO5dXi4T5m7pFsIV9kMKqsSybgLzQkLhf0=',
                'a state change',
            ],
            [
                "{\"trigger\": \"transcript.update\", \"bot_id\": \"bot_fixture\", \"data\": {\"speaker_name\": \"Chidiebere Okonkwo\", \"timestamp_ms\": 1079, \"transcription\": {\"transcript\": \"\\u1eb8 \\u1e63\\u00e9 / thank you\"}}}",
                'Y2wI+xq9wM9G0X3xX9Z9MyirOop6pLefxdDybebb8fc=',
                'a transcript with Yoruba diacritics and a slash',
            ],
            [
                "{\"trigger\": \"bot.state_change\", \"data\": {}, \"meta\": {}}",
                '2EsYYZz94A3MnEQHLexg85PwCiHR7nnZxIz/IOkMlnU=',
                'empty objects, which must not become empty arrays',
            ],
        ];
    }

    public function test_a_tampered_body_fails_even_with_a_genuine_signature(): void
    {
        [$body, $sig] = self::pythonSignedPayloads()[0];
        $this->assertFalse($this->verify(str_replace('ended', 'joining', $body), $sig, self::SECRET));
    }

    public function test_a_wrong_or_absent_signature_fails(): void
    {
        [$body] = self::pythonSignedPayloads()[0];
        $this->assertFalse($this->verify($body, base64_encode('not the signature'), self::SECRET));
        $this->assertFalse($this->verify($body, '', self::SECRET));
    }

    public function test_a_secret_that_is_not_base64_fails_rather_than_being_hashed_as_text(): void
    {
        [$body, $sig] = self::pythonSignedPayloads()[0];
        $this->assertFalse($this->verify($body, $sig, '!!! not base64 !!!'));
    }

    public function test_a_float_in_the_payload_is_a_known_and_asserted_limit(): void
    {
        // Python emits 1.0, PHP emits 1, so the canonical strings differ and the HMAC
        // cannot match. Attendee's own payload fields are integers; a transcription
        // provider's blob is passed through verbatim and could carry a float. Asserted
        // so the limit stays visible — it costs latency, never data, because the cron
        // re-fetches the same transcript.
        $body = '{"trigger": "transcript.update", "data": {"confidence": 1.0}}';
        $sig  = base64_encode(hash_hmac(
            'sha256',
            '{"data":{"confidence":1.0},"trigger":"transcript.update"}',   // as Python writes it
            (string) base64_decode(self::SECRET, true),
            true
        ));

        $this->assertFalse($this->verify($body, $sig, self::SECRET));
    }

    private function verify(string $raw, string $signature, string $secretB64): bool
    {
        $m = new \ReflectionMethod(InterviewBotController::class, 'signatureOk');
        $m->setAccessible(true);
        return (bool) $m->invoke(null, $raw, $signature, $secretB64);
    }
}
