<?php
declare(strict_types=1);

namespace Tests\Unit;

use AfricaGates\Services\{EventFlier, EventFlierLayout, EventFlierTheme, EventTicketDesign, EventTierPalette};
use Tests\TestCase;

/**
 * The flier's palette, asserted by sampling the accent space rather than by checking colours.
 *
 * ══════════════════════════════════════════════════════════════════════════════
 * WHY SAMPLING AND NOT EXAMPLES
 * ══════════════════════════════════════════════════════════════════════════════
 *
 * A palette generated by arithmetic will hand you white type on a pale yellow ground the
 * first time somebody picks pale yellow, and it will look correct in every test that checks
 * an image came back. Every fault this file has actually caught was on an accent nobody would
 * have thought to write down:
 *
 *   - `bold` on a mid-lightness saturated hue (#237b22, #1d6fa5, #ff0000) collapsed `ink`,
 *     `mute` AND the highlight to white — one colour for the name, the title and the date —
 *     because on that ground nothing else clears 4.5:1. The fix was to band the lightness out
 *     of the middle, which nothing but a sweep would have suggested.
 *   - a gold event's `paper` flier came out olive, because one accent value was doing duty as
 *     both a graphic and a line of text and the text floor darkened it past recognition.
 *
 * So the sweep walks the hue wheel at several saturations and lightnesses, plus the greys and
 * the primaries, and asserts the FLOORS rather than the values. It is the same method
 * EventTierPalette's own tests use, for the same reason.
 */
final class EventFlierThemeTest extends TestCase
{
    /**
     * The accent space, sampled.
     *
     * @return list<string>
     */
    private function accents(): array
    {
        $out = [
            // The greys, including the two ends. No hue to build a highlight from.
            '#000000', '#ffffff', '#333333', '#888888', '#e6e6e6',
            // The platform's own default, which is the accent most events will actually have.
            EventTicketDesign::DEFAULT_ACCENT,
            // The house gold, and the emerald reserved for action.
            '#f3b416', '#237b22',
            // Saturated primaries — the worst case for `bold`, as the class note explains.
            '#ff0000', '#00ff00', '#0000ff', '#00ffcc', '#ff00ff',
        ];

        // The wheel. Every 40°, at two saturations and three lightnesses — the corners of the
        // space rather than a tour of colours somebody likes.
        for ($h = 0; $h < 360; $h += 40) {
            foreach ([0.35, 0.85] as $s) {
                foreach ([0.18, 0.48, 0.80] as $l) {
                    $out[] = EventTierPalette::fromHsl((float) $h, $s, $l);
                }
            }
        }

        return $out;
    }

    /** The worse of the two grounds — the canvas is a gradient, so both have to clear. */
    private function worst(string $hex, array $t): float
    {
        return min(
            EventTierPalette::contrast($hex, $t['ground_top']),
            EventTierPalette::contrast($hex, $t['ground_bot']));
    }

    // ══ the floors, on every accent and every style ══════════════════════════

    public function test_every_style_on_every_accent_clears_the_reading_floor(): void
    {
        // ── THE ASSERTION THE WHOLE FILE EXISTS FOR ──────────────────────────
        //
        // WCAG 1.4.3: 4.5:1 for normal text. The meta line is 26px in a 1080px image, which is
        // large on a screen and small on a phone — and a flier is looked at on a phone, so the
        // normal-text floor is the honest one.
        //
        // Against BOTH grounds. Checking one is how a `mute` that measured 4.6 at the top of
        // the plate measured 3.9 at the bottom, where half the meta line actually sits.
        $checked = 0;

        foreach ($this->accents() as $accent) {
            foreach (array_keys(EventFlierTheme::STYLES) as $style) {
                $t = EventFlierTheme::fromAccent($accent, $style, 'story');

                foreach (['ink', 'mute', 'accent_text'] as $token) {
                    $this->assertGreaterThanOrEqual(
                        4.5, round($this->worst($t[$token], $t), 2),
                        "$token on $accent/$style measured too low against its ground");
                    $checked++;
                }
            }
        }

        // The sweep has to actually be a sweep. A refactor that made accents() return two
        // entries would leave every assertion above passing and prove nothing.
        $this->assertGreaterThan(500, $checked);
    }

    public function test_the_graphic_accent_clears_the_non_text_floor_on_every_accent(): void
    {
        // WCAG 1.4.11: 3:1 for a graphic that carries meaning — the hairline rule and the
        // mark chip's fill. Deliberately a LOWER floor than the text one, which is what lets
        // the accent stay recognisably the colour the organiser chose. See the theme's note on
        // the fill/text split, which is this codebase's own `fill` vs `edge` distinction.
        foreach ($this->accents() as $accent) {
            foreach (array_keys(EventFlierTheme::STYLES) as $style) {
                $t = EventFlierTheme::fromAccent($accent, $style, 'story');
                $this->assertGreaterThanOrEqual(3.0, round($this->worst($t['accent'], $t), 2),
                    "the accent on $accent/$style is not a visible object on its ground");
            }
        }
    }

    public function test_the_chip_ink_is_guaranteed_against_the_chip_and_the_accent(): void
    {
        // Both are FILLS an organiser's colour decides, and both carry a word: "Ticket
        // confirmed" and the tier name. A chip nobody can read is the failure
        // EventTierPalette::ink() exists to make impossible — it falls through to pure black
        // rather than approximating with a luminance threshold.
        foreach ($this->accents() as $accent) {
            foreach (array_keys(EventFlierTheme::STYLES) as $style) {
                $t = EventFlierTheme::fromAccent($accent, $style, 'story');
                $this->assertGreaterThanOrEqual(4.5,
                    round(EventTierPalette::contrast($t['on_accent'], $t['accent']), 2),
                    "the mark chip's text on $accent/$style");
                $this->assertGreaterThanOrEqual(4.5,
                    round(EventTierPalette::contrast($t['chip_ink'], $t['chip_fill']), 2),
                    "the tier chip's text on $accent/$style");
            }
        }
    }

    public function test_the_muted_line_is_tellable_from_the_primary_one(): void
    {
        // Both are pushed toward the same end of the range by the contrast floor, so they can
        // converge — and a "muted" line the same colour as the primary one is not a hierarchy,
        // it is two lines that look like a mistake. This is the fault that shipped in `bold`.
        //
        // Not asserted as an absolute: legibility wins, and separateFrom() stops moving the
        // moment another step would drop below the text floor. So the claim is the weaker true
        // one — the vast majority separate, and none of them separate at the cost of the
        // floor, which the test above already proves.
        $tight = 0;
        $total = 0;

        foreach ($this->accents() as $accent) {
            foreach (array_keys(EventFlierTheme::STYLES) as $style) {
                $t = EventFlierTheme::fromAccent($accent, $style, 'story');
                $total++;
                if (EventTierPalette::distance($t['mute'], $t['ink']) < 40.0) $tight++;
            }
        }

        $this->assertLessThan($total * 0.06, $tight,
            'the muted and primary inks collapse into one colour too often');
    }

    // ══ the palette is the EVENT'S, which is the whole point ═════════════════

    public function test_two_events_with_different_accents_get_different_palettes(): void
    {
        // Eleven hexes were hard-coded, so every flier for every event came out the same
        // colour on a platform where the tier chips, the selection light and the printed
        // ticket all already follow the organiser's accent.
        $a = EventFlierTheme::forEvent(['ticket_accent' => '#1d6fa5'], 'deep', 'story');
        $b = EventFlierTheme::forEvent(['ticket_accent' => '#8a2b6d'], 'deep', 'story');

        $this->assertNotSame($a['ground_bot'], $b['ground_bot']);
        $this->assertNotSame($a['accent'], $b['accent']);
        $this->assertGreaterThan(40.0,
            EventTierPalette::distance($a['ground_bot'], $b['ground_bot']),
            'two events must not get grounds that read as the same colour');
    }

    public function test_an_event_with_no_accent_gets_the_platform_default(): void
    {
        // Not an error and not a blank: EventTicketDesign::colour() is the one place a missing
        // or malformed accent is resolved, and the flier goes through it rather than deciding
        // for itself what "no colour" means.
        $none = EventFlierTheme::forEvent(['ticket_accent' => ''], 'deep', 'story');
        $dflt = EventFlierTheme::fromAccent(EventTicketDesign::DEFAULT_ACCENT, 'deep', 'story');

        $this->assertSame($dflt, $none);
        $this->assertSame($dflt, EventFlierTheme::forEvent(null, 'deep', 'story'));
        $this->assertSame($dflt, EventFlierTheme::forEvent(['ticket_accent' => 'nonsense'], 'deep', 'story'));
    }

    public function test_a_monochrome_event_keeps_a_monochrome_ground_and_the_house_accent(): void
    {
        // A grey highlight on a grey ground is not a highlight — it is the ink again, one step
        // darker. EventTierPalette answers the same problem by keeping an achromatic ladder
        // achromatic, because inventing hues there would produce six colours matching nothing
        // on the event. Here it inverts: the accent slot is where the platform's own name is
        // set, and the Africa GATES gold on a charcoal flier reads as branding.
        foreach (['#000000', '#333333', '#888888', '#ffffff'] as $grey) {
            $t = EventFlierTheme::fromAccent($grey, 'deep', 'story');

            [, $gs] = EventTierPalette::toHsl($t['ground_bot']);
            $this->assertLessThan(0.05, $gs, "the ground for $grey must stay grey");

            [$ah] = EventTierPalette::toHsl($t['accent']);
            [$hh] = EventTierPalette::toHsl(EventFlierTheme::HOUSE);
            $this->assertEqualsWithDelta($hh, $ah, 12.0,
                "the highlight for $grey must be the house gold's hue");
        }
    }

    // ══ the styles, and what a format can offer ══════════════════════════════

    public function test_a_format_with_no_photo_does_not_offer_the_photo_style(): void
    {
        // An option in a picker that changes nothing when chosen is worse than one that is
        // absent: the person presses it, nothing moves, and they conclude the flier is broken.
        $this->assertArrayHasKey('tint', EventFlierTheme::stylesFor('story'));
        $this->assertArrayHasKey('tint', EventFlierTheme::stylesFor('square'));
        $this->assertArrayNotHasKey('tint', EventFlierTheme::stylesFor('plain'));
    }

    public function test_a_style_a_format_cannot_draw_falls_back_to_that_formats_default(): void
    {
        // A hand-written URL is the caller here. It gets a flier, not an error — and not a
        // half-applied style either.
        $this->assertSame('paper', EventFlierTheme::style('tint', 'plain'));
        $this->assertSame('tint',  EventFlierTheme::style('tint', 'story'));
        $this->assertSame('deep',  EventFlierTheme::style('nonsense', 'story'));
        $this->assertSame('paper', EventFlierTheme::style('', 'plain'));
        $this->assertSame('bold',  EventFlierTheme::style('BOLD', 'plain'));
    }

    public function test_the_photo_tint_is_only_set_where_there_is_a_photo_to_tint(): void
    {
        // Declared and unread is the most expensive shape of bug in this codebase; declared
        // where it cannot apply is the same fault wearing a different hat — the renderer would
        // grey and re-colour a region the format does not have.
        $this->assertNotNull(EventFlierTheme::fromAccent('#1d6fa5', 'tint', 'story')['photo_tint']);
        $this->assertNull(EventFlierTheme::fromAccent('#1d6fa5', 'tint', 'plain')['photo_tint']);
        $this->assertNull(EventFlierTheme::fromAccent('#1d6fa5', 'deep', 'story')['photo_tint']);
    }

    public function test_the_qr_plate_never_follows_the_event(): void
    {
        // A symbol needs dark modules on a light field: the specification, not a preference.
        // Every other pixel on the flier follows the organiser's accent; a code that scans is
        // worth more than a code that matches.
        foreach ($this->accents() as $accent) {
            foreach (array_keys(EventFlierTheme::STYLES) as $style) {
                $t = EventFlierTheme::fromAccent($accent, $style, 'story');
                $this->assertSame('#FFFFFF', $t['qr_plate'], $accent . '/' . $style);
                $this->assertSame('#000000', $t['qr_ink'], $accent . '/' . $style);
            }
        }
    }

    public function test_the_photo_slot_no_longer_decides_whether_the_flier_is_light(): void
    {
        // `$paper = $fmt === 'plain'` meant there was no such thing as a dark no-photo flier
        // or a light one with a photo in it, and neither of those is a bad idea. The style
        // decides the ground now; the format decides the shape.
        $this->assertTrue(EventFlierTheme::fromAccent('#237b22', 'deep', 'plain')['dark'],
            'a no-photo flier must be able to be dark');
        $this->assertFalse(EventFlierTheme::fromAccent('#237b22', 'paper', 'story')['dark'],
            'a flier with a photo must be able to be light');
    }

    // ══ the format resolver both the renderer and the route use ══════════════

    public function test_the_drawn_format_is_resolved_in_one_place(): void
    {
        // The route has to normalise the style against the format that will be DRAWN, not the
        // one that was asked for, or the X-Flier-Style header describes an image that is not
        // in the body. Two computations of that fallback is how they would come to disagree.
        $this->assertSame('plain',  EventFlier::format('story', false));
        $this->assertSame('plain',  EventFlier::format('square', false));
        $this->assertSame('story',  EventFlier::format('story', true));
        $this->assertSame('plain',  EventFlier::format('plain', true));
        $this->assertSame('plain',  EventFlier::format('nonsense', true));
    }

    public function test_every_style_is_offered_with_a_label_and_a_note(): void
    {
        // The note says what the style DOES. "Dark, cinematic" is choosable; "Deep" alone is
        // not, and four unlabelled colour chips is a guess rather than a choice.
        foreach (EventFlierTheme::STYLES as $key => $meta) {
            $this->assertNotSame('', trim($meta['label']), $key);
            $this->assertNotSame('', trim($meta['note']), $key);
        }

        // And every format's picker has something in it.
        foreach (EventFlierLayout::FORMATS as $fmt) {
            $this->assertGreaterThanOrEqual(3, count(EventFlierTheme::swatches(
                ['ticket_accent' => '#1d6fa5'], $fmt)), $fmt);
        }
    }

    public function test_the_picker_swatches_are_this_events_real_colours(): void
    {
        // Computed here rather than written into the template as approximations. A picker
        // showing a generic dark-green chip beside a flier that comes out teal is a control
        // that lies about its own outcome.
        $sw = EventFlierTheme::swatches(['ticket_accent' => '#8a2b6d'], 'story');

        foreach ($sw as $row) {
            $t = EventFlierTheme::fromAccent('#8a2b6d', $row['key'], 'story');
            $this->assertSame($t['ground_bot'], $row['ground'], $row['key']);
            $this->assertSame($t['ink'], $row['ink'], $row['key']);
            $this->assertSame($t['accent'], $row['accent'], $row['key']);
        }
    }

    public function test_the_renderer_holds_no_colours_of_its_own(): void
    {
        // ── THE ASSERTION THAT KEEPS THE PALETTE IN ONE PLACE ────────────────
        //
        // Thirteen hexes lived on EventFlierLayout and eleven were used directly by the
        // renderer. Twelve of the thirteen have no reader now, so they are gone — a constant
        // nothing reads is the shape §17 of the index lists six shipped instances of, and a
        // dead palette beside a live renderer is the next person's afternoon.
        //
        // The one survivor is the house gold, which the theme reads for an event whose own
        // accent has no hue. This asserts that state rather than trusting it: a literal hex
        // reintroduced into the renderer would take that flier off the organiser's colour and
        // nothing else here would notice.
        $src = (string) file_get_contents(dirname(__DIR__, 2) . '/src/Services/EventFlier.php');

        // Comments quote hexes — the docblocks explain what the old palette was — so they go
        // first. Same reason the generator test strips Twig comments before scanning.
        $src = (string) preg_replace('~/\*[\s\S]*?\*/~', '', $src);
        $src = (string) preg_replace('~^\s*//.*$~m', '', $src);

        $this->assertDoesNotMatchRegularExpression('~#[0-9a-fA-F]{6}~', $src,
            'the renderer must take every colour from EventFlierTheme');
        $this->assertDoesNotMatchRegularExpression('~EventFlierLayout::C_|\$L::C_~', $src,
            'and not from the layout either');
    }

    public function test_the_layout_keeps_only_the_house_accent(): void
    {
        $src = (string) file_get_contents(
            dirname(__DIR__, 2) . '/src/Services/EventFlierLayout.php');

        preg_match_all('~public const (C_[A-Z_]+)~', $src, $m);
        $this->assertSame(['C_GOLD'], $m[1],
            'the flier palette is derived now — a leftover constant here has no reader');
        $this->assertSame(EventFlierLayout::C_GOLD, EventFlierTheme::HOUSE);
    }
}
